name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2           # ⬅️ update to v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true                  # ⬅️ recommended: get binaries when possible

      # ⬅️ ADD THIS STEP (macOS system libraries for curl/openssl headers)
      - name: System dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install curl openssl

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "httr", "jsonlite", "methods"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
