name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['3.5.1','4.1.1']

    steps:
      - uses: actions/checkout@v4

      # ✅ Add this
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true

      - name: System dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config openssl@3
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix openssl@3)/include"           >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix openssl@3)/lib"                >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck","rmarkdown","knitr","httr","jsonlite","methods"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
